### ISSUE TITLE
omg

### ISSUE THREAD

**Issue by JBYT27** [darkdarcool/GitData#1]
lol this is basically a gitapi module xD

**Comment by darkdarcool** [comment]
Yea, if you wanna work on this I can add you

**Comment by JBYT27** [comment]
Oki

**Comment by darkdarcool** [comment]
I'll add tommorow

**Comment by JBYT27** [comment]
btw, r u gonna upload to pypi?

**Comment by darkdarcool** [comment]
already did, but this is still a work in progress, and there are many more queries to make

**Comment by darkdarcool** [comment]
I invited to the repl BTW

**Comment by JBYT27** [comment]
oki
