### ISSUE TITLE
a very buggy bug

### ISSUE THREAD

**Issue by iop3** [darkdarcool/GitData#2]
So i pip installed it `pip install GitData`. But it still returned a error when i ran this piece of code.
```py
from GitData import readUser, parse 
user = readUser("darkdarcool") # You can change it to anyones username! 
user = parse(user) # Parse it 
print(user.username()) # Print the user's name!
```
![image](https://user-images.githubusercontent.com/79815764/122600916-5b5b2780-d025-11eb-8c48-cbcf038c3445.png)

**Comment by iop3** [comment]
[also im pretty sure there is another pip module named "gitdata". And im 95% sure that is not urs.](https://pypi.org/project/gitdata/)

**Comment by darkdarcool** [comment]
I haven't published this code, that's just a placeholder so no one takes my name, I'll tell you when it comes out

**Comment by darkdarcool** [comment]
[this](https://pypi.org/project/GitGrabber/) is link, but still import it in code the same way

**Comment by iop3** [comment]
oh ok lul nice name "gitgrabber" xD

**Comment by darkdarcool** [comment]
lol thx
